### ISSUE TITLE
Make it easier to parse query parameters into an object (with hooks?)

### ISSUE THREAD

**Issue by ajusa** [treeform/webby#23]
In the style of [jsony](https://github.com/treeform/jsony) and [tabby](https://github.com/treeform/tabby), it'd be really nice to get some sort of built in way to parse either a query string directly into an object, or the QueryParams type into an object. The trickier part is also supporting sequences, as those end up repeating keys.

I can see a version of this was written in the debby examples (https://github.com/treeform/debby/blob/master/examples/admin.nim#L138-L143), so it'd be nice to extract it out and make it more generic if possible. I have a version I've been using in my projects:

```nim
proc parseHook(params: QueryParams, name: string, v: var int) = v = parseInt(params[name])
proc parseHook(params: QueryParams, name: string, v: var string) = v = params[name]
proc parseHook(params: QueryParams, name: string, v: var bool) = v = name in params
proc parseHook[T](params: QueryParams, name: string, v: var seq[T]) =
  for i, (k, _) in params:
    if k == name:
      var val: T
      when compiles(params.toBase[i .. ^1].QueryParams.fromQuery(name, val)):
        params.toBase[i .. ^1].QueryParams.fromQuery(name, val)
      v.add(val)
proc fromQuery[T](params: QueryParams, objType: typedesc[T]): T =
  for fieldName, value in result.fieldPairs: parseHook(params, fieldName, value)

```

It's a little hacky (the `when compiles` is in there to prevent parsing objects within sequences), so if there's a better way of doing it that could be included in webby itself that would be really neat!

**Comment by guzba** [comment]
Are you receiving complex query strings in requests? This seems to be JSON body + POST request territory at first glance.

**Comment by ajusa** [comment]
Not _particularly_ complex information, but I do have some boolean flags, some string fields, a numeric field, and then a repeated field. Nothing is nested or anything crazy like that, though this is a (form) post request.

A use case I haven't quite built yet does have a similar set of concerns for a get request - more specifically, it filters a list of resources based on a combination of tags (which are repeated query parameters) and min/max numeric filters.

**Comment by guzba** [comment]
Would it be possible to base64 encode JSON as a ?q=encodedqueryjson instead of using form encoding directly? Form encoding is just kind of not something I'd be really seeking to use for anything even slightly complex if I could avoid it. Obviously this is not always possible but something to consider if it has not been seen as an option.

**Comment by ajusa** [comment]
I was able to get that working, and it is quite nice. I'm using HTMX with their `json-enc` extension, which basically turns any requests from HTML form data into JSON. 

Only downside is that the output JSON is all strings, so at the top of my codebase I've declared the following:

```nim
proc parseHook*(s: string, i: var int, v: var int) =
  var str: string
  parseHook(s, i, str)
  v = parseInt(str)

proc parseHook*(s: string, i: var int, v: var bool) =
  var str: string
  parseHook(s, i, str)
  v = true
  ```
  
  Not the end of the world, and if I wanted to be more strict about it I'd declare new types like "FormNumber" and "FormBoolean" which would be distincts to override.
  
  You've solved my problem in the end, so I'm going to close the issue. Thanks for the suggestion!

**Comment by guzba** [comment]
Once [Sunny](https://github.com/guzba/sunny) is added to the Nim package directory here https://github.com/nim-lang/packages/pull/2828 using the string field tag would at least resolve the numbers-as-strings problem easily. Not for bools now though, that is more uncommon than numbers-as-strings.

Sunny is basically taking the Golang field tags and bringing them to Nim while still enabling hooks like Jsony. If you like the tags, Sunny is a nice option, if prefer all-hooks-all-the-time then Jsony is the way to go. Just a matter of preference, both aren't going away.
